# Generated by Django 5.2 on 2025-04-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="prerequisites",
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of course codes that must be completed before enrolling in this course.",
            ),
        ),
    ]
